"""empty message

Revision ID: 3aa398a9db1e
Revises: d8cbf5acfcaf
Create Date: 2024-03-16 18:59:21.978823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa398a9db1e'
down_revision = 'd8cbf5acfcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('filiere_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_classe_filiere_id_filiere'), 'filiere', ['filiere_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_classe_niveau_id_niveau'), 'niveau', ['niveau_id'], ['id'])

    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anneeScolaire_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('semestre_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('professeur_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cours_professeur_id_professeur'), 'professeur', ['professeur_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cours_anneeScolaire_id_annee_scolaire'), 'annee_scolaire', ['anneeScolaire_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cours_module_id_module'), 'module', ['module_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_cours_semestre_id_semestre'), 'semestre', ['semestre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cours', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cours_semestre_id_semestre'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cours_module_id_module'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cours_anneeScolaire_id_annee_scolaire'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cours_professeur_id_professeur'), type_='foreignkey')
        batch_op.drop_column('professeur_id')
        batch_op.drop_column('module_id')
        batch_op.drop_column('semestre_id')
        batch_op.drop_column('anneeScolaire_id')

    with op.batch_alter_table('classe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classe_niveau_id_niveau'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_classe_filiere_id_filiere'), type_='foreignkey')
        batch_op.drop_column('filiere_id')
        batch_op.drop_column('niveau_id')

    # ### end Alembic commands ###
