"""empty message

Revision ID: 9b4b9c3dea33
Revises: 3aa398a9db1e
Create Date: 2024-03-16 19:01:45.843425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4b9c3dea33'
down_revision = '3aa398a9db1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enseignement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anneeScolaire_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('professeur_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_enseignement_professeur_id_professeur'), 'professeur', ['professeur_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_enseignement_classe_id_classe'), 'classe', ['classe_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_enseignement_anneeScolaire_id_annee_scolaire'), 'annee_scolaire', ['anneeScolaire_id'], ['id'])

    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anneeScolaire_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classe_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('etudiant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_inscription_etudiant_id_etudiant'), 'etudiant', ['etudiant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inscription_classe_id_classe'), 'classe', ['classe_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_inscription_anneeScolaire_id_annee_scolaire'), 'annee_scolaire', ['anneeScolaire_id'], ['id'])

    with op.batch_alter_table('semestre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niveau_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_semestre_niveau_id_niveau'), 'niveau', ['niveau_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semestre', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_semestre_niveau_id_niveau'), type_='foreignkey')
        batch_op.drop_column('niveau_id')

    with op.batch_alter_table('inscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_inscription_anneeScolaire_id_annee_scolaire'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inscription_classe_id_classe'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_inscription_etudiant_id_etudiant'), type_='foreignkey')
        batch_op.drop_column('etudiant_id')
        batch_op.drop_column('classe_id')
        batch_op.drop_column('anneeScolaire_id')

    with op.batch_alter_table('enseignement', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_enseignement_anneeScolaire_id_annee_scolaire'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_enseignement_classe_id_classe'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_enseignement_professeur_id_professeur'), type_='foreignkey')
        batch_op.drop_column('classe_id')
        batch_op.drop_column('professeur_id')
        batch_op.drop_column('anneeScolaire_id')

    # ### end Alembic commands ###
